### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by samarthsarin** [eschizoid/jiralexa#2]
Hi All,

Can someone please help me with setting up this project.
I want to know what is the exact url to be passed in config.js as I am always getting an error that the alexa skill was unable to launch my url and response code is never 200.
Please help me its urgent.

Thank you

**Comment by eschizoid** [comment]
Hi @samarthsarin, if you are using the apache jira, then you can keep the existing one:
```
https://issues.apache.org/jira/rest/api/2/search
```

**Comment by samarthsarin** [comment]
I am using jira by atlassian. So the url is something like this https://
{myhost}.{mycloud}.com

**Comment by eschizoid** [comment]
Then you just need to change these properties (user, password url):

https://github.com/eschizoid/jiralexa/blob/master/src/config.json#L2
https://github.com/eschizoid/jiralexa/blob/master/src/config.json#L3
https://github.com/eschizoid/jiralexa/blob/master/src/config.json#L5

Hope this helps

**Comment by samarthsarin** [comment]
Ok thanks.
Can you also help me that my website is VPN protected. So will alexa be
able to connect with that. Is there any way to do so

**Comment by eschizoid** [comment]
AWS infrastructure has to be reachable within your VPN, otherwise this won't work :(

**Comment by samarthsarin** [comment]
How can i achieve that?
How can my alexa connect to a website which is protected with VPN?
